<?xml version="1.0" encoding="utf-8"?><Database Name="alo895cb_powerfultrainer" Class="DataEntityDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=112.78.2.50,1433;Initial Catalog=alo895cb_powerfultrainer;Persist Security Info=True;User ID=alo895cb_powerfultrainer" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="alo895cb_powerfultrainerConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="alo895cb_powerfultrainer.Friend" Member="Friends">
    <Type Name="Friend">
      <Column Name="Username" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FriendUser" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IsWaiting" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="RequestTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="alo895cb_powerfultrainer.WorkoutPlan" Member="WorkoutPlans">
    <Type Name="WorkoutPlan">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Data" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ParentPlan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Image" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Owner" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ShareTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AvgHeartRate" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TotalCals" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TotalSteps" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="alo895cb_powerfultrainer.Report" Member="Reports">
    <Type Name="Report">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PlanID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PlanName" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BeginTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Duration" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AvgHeartRate" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TotalCals" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TotalSteps" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="IsGoal" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="alo895cb_powerfultrainer.Account" Member="Accounts">
    <Type Name="Account">
      <Column Name="Username" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Birthday" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Gender" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Type" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AccessToken" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ExpireDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Avatar" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="MSAccessToken" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="MSRefreshToken" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="MSExpireDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="alo895cb_powerfultrainer.Exercise" Member="Exercises">
    <Type Name="Exercise">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="BodyParts" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Thumbnail" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Image" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="DifficultyLevel" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Equipment" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Focus" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsRest" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Url" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Phone" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="VideoUrl" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
</Database>